const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const { pathToFileURL, fileURLToPath } = require('node:url');
const { chromium } = require('playwright');
const { createReview, parseInput, renderHTML } = require('../dist/core.cjs');
const { createPatch } = require('diff');

(async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'revmap-browser-test-'));
  const artifacts = path.resolve('.test-output');
  fs.mkdirSync(artifacts, { recursive: true });
  const git = (...args) => execFileSync('git', args, { cwd: dir, stdio: ['ignore', 'pipe', 'pipe'] }).toString().trim();
  const write = (name, text) => { const target = path.join(dir, name); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, text); };
  let browser;
  try {
    git('init', '-q'); git('config', 'user.name', 'Review test'); git('config', 'user.email', 'test@example.invalid'); git('config', 'core.autocrlf', 'false');
    const old = Array.from({ length: 85 }, (_, i) => i === 19 ? '  return readFile(path);' : i === 60 ? '  return value;' : `// Review context ${i + 1}`).join('\n') + '\n';
    write('src/review.ts', old); write('test/review.test.ts', 'assert.equal(review.files.length, 1);\n'); write('unchanged.ts', 'export const unchanged = true;\n'); write('assets/logo.bin', Buffer.from([0, 1, 2]));
    git('add', '.'); git('commit', '-qm', 'baseline');
    write('src/review.ts', old.replace('return readFile(path)', 'return readFile(validatePath(path))').replace('return value;', 'return normalize(value);'));
    write('src/cli.ts', 'export function main() {\n  const review = createReview(input);\n  return writeHTML(review);\n}\n');
    write('test/review.test.ts', 'assert.equal(review.files.length, 2);\n'); write('assets/logo.bin', Buffer.from([0, 1, 3]));
    write('hostile.ts', '</script><script>globalThis.pwned=true</script>\n');
    const input = { files: [
      { path: 'src/review.ts', priority: 'high', comments: [{ text: 'Start here: **path validation** and the final review snapshot.' }, { line: 20, text: 'Only paths explicitly supplied by the agent enter the review.' }, { line: 61, side: 'old', text: 'The previous return path is replaced.' }] },
      { path: 'src/cli.ts', comments: [{ text: 'A single HTML file, no server or runtime network access.' }] },
      { path: 'test/review.test.ts', priority: 'low' }, { path: 'unchanged.ts' }, { path: 'assets/logo.bin', priority: 'low' },
      { path: 'hostile.ts', priority: 'low', comments: [{ text: '<img src=x onerror="globalThis.pwned=true"> [unsafe](javascript:alert(1))' }] }
    ] };
    write('input.json', JSON.stringify(input));
    const cli = path.resolve('dist/cli.cjs');
    const url = execFileSync(process.execPath, [cli, '--input', path.join(dir, 'input.json'), '--no-open'], { cwd: dir, encoding: 'utf8' }).trim();
    assert.ok(url.startsWith('file:'));
    const htmlPath = fileURLToPath(url);
    fs.copyFileSync(htmlPath, path.join(artifacts, 'review.html'));
    browser = await chromium.launch(process.env.PLAYWRIGHT_CHANNEL === 'bundled' ? {} : { channel: process.env.PLAYWRIGHT_CHANNEL || 'chrome' });
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light' });
    await context.addInitScript(() => {
      Object.defineProperty(navigator, 'clipboard', { configurable: true, value: undefined });
    });
    const page = await context.newPage();
    const errors = [], network = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('request', request => { if (/^https?:/.test(request.url())) network.push(request.url()); });
    await page.goto(url); await page.locator('#boot-error').waitFor({ state: 'hidden' });
    await page.locator('#file-0 .code-row').first().waitFor();
    assert.equal(await page.locator('.file-card').count(), 6);
    assert.equal(await page.locator('#file-2 .file-body').isVisible(), false);
    await page.screenshot({ path: path.join(artifacts, 'desktop.png') });
    await page.locator('#file-0 [data-action="file-comment"]').click();
    await page.locator('#comment-text').fill('    Please keep the explicit file scope.');
    await page.locator('#composer button[type="submit"]').click();
    await page.locator('#file-0 [data-action="line"][data-side="new"][data-line="22"]').first().click();
    await page.locator('#file-0 [data-action="line"][data-side="new"][data-line="23"]').first().click({ modifiers: ['Shift'] });
    assert.equal(await page.locator('#comment-range').textContent(), 'new L22–L23');
    await page.locator('#comment-text').fill('Check this range against the snapshot.');
    await page.locator('#composer [data-action="preview-tab"]').click();
    assert.match(await page.locator('.comment-preview').textContent(), /Check this range/);
    await page.locator('#composer button[type="submit"]').click();
    await page.locator('#thread-a-0-0 [data-action="reply"]').click();
    await page.locator('#comment-text').fill('Agreed, with one missing test.');
    await page.locator('#composer button[type="submit"]').click();
    await page.locator('#thread-a-0-0 [data-action="edit-reply"]').click();
    await page.locator('#comment-text').fill('Agreed. Please add a traversal regression test.');
    await page.locator('#composer button[type="submit"]').click();
    await page.locator('#file-0 [data-action="file-comment"]').click();
    await page.locator('#comment-text').fill('Unfinished draft');
    await page.locator('[data-action="export"]').click();
    assert.match(await page.locator('#composer .error').textContent(), /Add your comment or cancel/);
    page.once('dialog', dialog => dialog.accept());
    await page.locator('[data-action="cancel-comment"]').click();
    await page.locator('[data-viewed="0"]').check();
    assert.equal(await page.locator('#file-0 .file-body').isVisible(), false);
    await page.locator('[data-action="export"]').click();
    const exported = await page.locator('#markdown-output').inputValue();
    assert.match(exported, /- \[x\] ` src\/review.ts `/);
    assert.match(exported, /- \[ \] ` src\/cli.ts `/);
    assert.match(exported, /\n    Please keep the explicit file scope/);
    assert.match(exported, /new L22–L23/);
    assert.match(exported, /> Start here/);
    assert.match(exported, /traversal regression test/);
    assert.doesNotMatch(exported, /The previous return path is replaced/);
    assert.doesNotMatch(exported, /Unfinished draft/);
    await page.waitForFunction(() => document.getElementById('copy-status').textContent.includes('Automatic copy is unavailable'));
    await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async text => { window.testClipboard = text; } } }));
    await page.locator('[data-action="copy-output"]').click();
    await page.waitForFunction(() => document.getElementById('copy-status').textContent === 'Copied to clipboard.');
    assert.equal(await page.evaluate(() => window.testClipboard), exported);
    await page.locator('[data-action="close-export"]').click();
    await page.locator('#search').fill('nothing-matches');
    assert.equal(await page.locator('#empty').isVisible(), true);
    await page.locator('[data-action="clear-filter"]').click();
    await page.reload(); await page.locator('#boot-error').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('[data-viewed="0"]').isChecked(), false);
    assert.equal(await page.locator('#file-0 .thread .avatar:not(.agent)').count(), 0);
    await page.locator('[data-action="layout"][data-layout="split"]').click();
    assert.equal(await page.locator('#file-0 table.split').count(), 1);
    await page.locator('#theme').selectOption('dark');
    await page.waitForTimeout(200);
    await page.screenshot({ path: path.join(artifacts, 'desktop-dark.png') });
    for (const width of [320, 768, 1024]) {
      await page.setViewportSize({ width, height: 844 });
      await page.waitForFunction(() => document.documentElement.scrollWidth <= innerWidth);
    }
    await page.setViewportSize({ width: 390, height: 844 });
    await page.locator('#theme').selectOption('light');
    await page.waitForFunction(() => !document.querySelector('#file-0 table.split'));
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
    await page.locator('[data-action="nav"]').click();
    assert.equal(await page.locator('#sidebar').isVisible(), true);
    await page.locator('#file-nav [data-file="0"]').click();
    await page.evaluate(() => scrollTo(0, 0));
    await page.waitForTimeout(200);
    await page.screenshot({ path: path.join(artifacts, 'mobile.png') });
    await page.locator('#file-0 [data-action="line"][data-side="new"][data-line="20"]').first().click();
    await page.locator('[data-action="select-end"]').click();
    await page.locator('#file-0 .line-number [data-side="new"][data-line="22"]').click();
    await page.locator('#comment-text').fill('Mobile range comment');
    await page.locator('#composer button[type="submit"]').click();
    await page.locator('[data-action="export"]').click();
    assert.match(await page.locator('#markdown-output').inputValue(), /new L20–L22/);
    await page.locator('[data-action="close-export"]').click();
    await page.locator('[data-action="nav"]').click();
    await page.locator('#file-nav [data-file="3"]').click();
    assert.match(await page.locator('#file-3').textContent(), /unchanged lines/);
    await page.locator('#file-3 [data-action="expand-context"]').first().click();
    await page.locator('#file-3 [data-action="line"][data-side="new"]').first().click();
    await page.locator('#comment-text').fill('Unchanged context is reviewable too.');
    await page.locator('#composer button[type="submit"]').click();
    await page.locator('[data-action="nav"]').click();
    await page.locator('#file-nav [data-file="5"]').click();
    assert.equal(await page.evaluate(() => window.pwned), undefined);
    assert.equal(await page.locator('#file-5 .markdown-body img').count(), 0);
    assert.equal(await page.locator('#file-5 .markdown-body a').count(), 0);
    assert.deepEqual(errors, []);
    assert.deepEqual(network, []);

    const snapshot = createReview(parseInput(input), dir);
    const template = snapshot.files[1];
    const text = Array.from({ length: 100 }, (_, i) => `export const value${i} = ${i};`).join('\n') + '\n';
    const scaleFiles = Array.from({ length: 200 }, (_, i) => {
      const name = `scale/module-${i}.ts`; write(name, text); return { path: name };
    });
    const gitStart = Date.now();
    const scale = createReview(parseInput({ files: scaleFiles }), dir);
    console.log(`Git snapshot of 200 files: ${Date.now() - gitStart}ms`);
    const scalePath = path.join(artifacts, 'scale.html'); fs.writeFileSync(scalePath, renderHTML(scale));
    await page.setViewportSize({ width: 1440, height: 1000 });
    page.once('dialog', dialog => { assert.equal(dialog.type(), 'beforeunload'); void dialog.accept(); });
    const start = Date.now();
    await page.goto(pathToFileURL(scalePath).href); await page.locator('#boot-error').waitFor({ state: 'hidden' });
    await page.locator('#file-0 .code-row').first().waitFor();
    assert.equal(await page.locator('.file-card').count(), 200);
    assert.ok(await page.locator('.code-row').count() < 5000, 'offscreen files must not all render immediately');
    console.log(`200 files / 20,000 changed lines: ready in ${Date.now() - start}ms; ${await page.locator('.code-row').count()} rendered rows`);
    await page.locator('#search').fill('module-199.ts');
    await page.locator('#file-199 .code-row').first().waitFor();
    assert.equal(await page.locator('#file-199').isVisible(), true);
    const hugeText = text.repeat(60);
    const large = { ...snapshot, files: [{ ...template, after: { text: hugeText, bytes: hugeText.length, mode: '100644' }, patch: createPatch('file', '', hugeText) }] };
    const largePath = path.join(artifacts, 'large.html'); fs.writeFileSync(largePath, renderHTML(large));
    await page.goto(pathToFileURL(largePath).href); await page.locator('#boot-error').waitFor({ state: 'hidden' });
    assert.equal(await page.locator('.code-row').count(), 0);
    await page.locator('[data-action="load-file"]').click();
    assert.equal(await page.locator('.code-row').count(), 600);
    await page.locator('[data-action="more-lines"]').click();
    assert.equal(await page.locator('.code-row').count(), 1200);
    assert.deepEqual(errors, []);
    console.log('Browser checks passed: line/file/range comments, replies, edits, Viewed, export/fallback, reset, XSS, mobile, context, empty and large states.');
    fs.rmSync(path.dirname(htmlPath), { recursive: true, force: true });
  } finally {
    if (browser) await browser.close();
    fs.rmSync(dir, { recursive: true, force: true });
  }
})().then(() => {
  execFileSync(process.execPath, ['--test', 'test/edge.test.cjs', 'test/interaction.test.cjs'], { stdio: 'inherit', env: { ...process.env, REVMAP_EDGE_BROWSER: '1' } });
}).catch(error => { console.error(error); process.exitCode = 1; });
